// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAC6lNu5EP3A6Xm0H1R--RkLspODB3Vwgs',
    appId: '1:319502601680:web:36a3f71d3e3848e7cdbdd5',
    messagingSenderId: '319502601680',
    projectId: 'event-app-b0c2c',
    authDomain: 'event-app-b0c2c.firebaseapp.com',
    storageBucket: 'event-app-b0c2c.firebasestorage.app',
    measurementId: 'G-5F559B2S5P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHsY2fvoGUowYE7uGvvjIJ-kx2ugCh-js',
    appId: '1:319502601680:android:4d16215044be20cacdbdd5',
    messagingSenderId: '319502601680',
    projectId: 'event-app-b0c2c',
    storageBucket: 'event-app-b0c2c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCl7vxERp_l-6zs41TltPOMiKMPjYLPXUY',
    appId: '1:319502601680:ios:60d515fc75a84afdcdbdd5',
    messagingSenderId: '319502601680',
    projectId: 'event-app-b0c2c',
    storageBucket: 'event-app-b0c2c.firebasestorage.app',
    iosBundleId: 'com.example.mae',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCl7vxERp_l-6zs41TltPOMiKMPjYLPXUY',
    appId: '1:319502601680:ios:60d515fc75a84afdcdbdd5',
    messagingSenderId: '319502601680',
    projectId: 'event-app-b0c2c',
    storageBucket: 'event-app-b0c2c.firebasestorage.app',
    iosBundleId: 'com.example.mae',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAC6lNu5EP3A6Xm0H1R--RkLspODB3Vwgs',
    appId: '1:319502601680:web:ab8bc2b4485ddf74cdbdd5',
    messagingSenderId: '319502601680',
    projectId: 'event-app-b0c2c',
    authDomain: 'event-app-b0c2c.firebaseapp.com',
    storageBucket: 'event-app-b0c2c.firebasestorage.app',
    measurementId: 'G-C21QZGVR3J',
  );
}
