// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXBQXSBF1KTaUpmZ1lkMwQvRFBHGQBmOE',
    appId: '1:917709471486:web:64301debb5ecc446aeafaf',
    messagingSenderId: '917709471486',
    projectId: 'eventory-5e357',
    authDomain: 'eventory-5e357.firebaseapp.com',
    storageBucket: 'eventory-5e357.firebasestorage.app',
    measurementId: 'G-SBMX2SFXW4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiE3B7m7ry3OsEZYmXo5hkBc_dzPh7gkA',
    appId: '1:917709471486:android:d34d26bb5db474f1aeafaf',
    messagingSenderId: '917709471486',
    projectId: 'eventory-5e357',
    storageBucket: 'eventory-5e357.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDF9LkksRLGkm2kqUV87hl21KyobFaHktQ',
    appId: '1:917709471486:ios:827a6a193b00747eaeafaf',
    messagingSenderId: '917709471486',
    projectId: 'eventory-5e357',
    storageBucket: 'eventory-5e357.firebasestorage.app',
    iosBundleId: 'com.example.mae',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDF9LkksRLGkm2kqUV87hl21KyobFaHktQ',
    appId: '1:917709471486:ios:827a6a193b00747eaeafaf',
    messagingSenderId: '917709471486',
    projectId: 'eventory-5e357',
    storageBucket: 'eventory-5e357.firebasestorage.app',
    iosBundleId: 'com.example.mae',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXBQXSBF1KTaUpmZ1lkMwQvRFBHGQBmOE',
    appId: '1:917709471486:web:9f02524095661031aeafaf',
    messagingSenderId: '917709471486',
    projectId: 'eventory-5e357',
    authDomain: 'eventory-5e357.firebaseapp.com',
    storageBucket: 'eventory-5e357.firebasestorage.app',
    measurementId: 'G-4J6MQEJD61',
  );
}
