// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwzy9fawxapavx1QzsyOvqOve-yVymLHU',
    appId: '1:960465283252:web:de18828e5b4c5efd100fe1',
    messagingSenderId: '960465283252',
    projectId: 'apu-event-app',
    authDomain: 'apu-event-app.firebaseapp.com',
    storageBucket: 'apu-event-app.firebasestorage.app',
    measurementId: 'G-5S47FBEVKM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAj67_VXqAqr2tdutgVqwYxuB3qLwMR_C4',
    appId: '1:960465283252:android:a467573ad52e3fb0100fe1',
    messagingSenderId: '960465283252',
    projectId: 'apu-event-app',
    storageBucket: 'apu-event-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrvTuN9knqTE2wBkNc8CSQoyFakjcozAA',
    appId: '1:960465283252:ios:26061e832b9c4a11100fe1',
    messagingSenderId: '960465283252',
    projectId: 'apu-event-app',
    storageBucket: 'apu-event-app.firebasestorage.app',
    iosBundleId: 'com.example.mae',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrvTuN9knqTE2wBkNc8CSQoyFakjcozAA',
    appId: '1:960465283252:ios:26061e832b9c4a11100fe1',
    messagingSenderId: '960465283252',
    projectId: 'apu-event-app',
    storageBucket: 'apu-event-app.firebasestorage.app',
    iosBundleId: 'com.example.mae',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwzy9fawxapavx1QzsyOvqOve-yVymLHU',
    appId: '1:960465283252:web:bbd41ba65c8f2d20100fe1',
    messagingSenderId: '960465283252',
    projectId: 'apu-event-app',
    authDomain: 'apu-event-app.firebaseapp.com',
    storageBucket: 'apu-event-app.firebasestorage.app',
    measurementId: 'G-EBX4WWSLSP',
  );

}